# Generated by Django 3.1 on 2020-08-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simple_api', '0002_auto_20200823_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(max_length=200),
        ),
    ]
